/**
*  @file       version.js
*  @brief      The Version information module of the Ulog.
*  @author     Yiwei Chiao (ywchiao@gmail.com)
*  @date       06/04/2018 created.
*  @date       06/04/2018 last modified.
*  @version    0.1.0-alpha.436
*  @since      0.1.0
*  @copyright  MIT, © 2018 Yiwei Chiao
*  @details
*
*  The Version information module of the Ulog.
*
*  This file is automatically generated. DONOT edit this by hand.
**/
'use strict';

export default {
  name: 'Ulog',
  version: '0.1.0',
  description: 'A blog system.',
  author: {
    name: 'Yiwei Chiao',
    email: 'ywchiao@gmail.com'
  },
  license: 'MIT',
  copyright: '2018',
  built: '06/04/2018'
};

// app/about.js
